import type { GovernmentLocation } from "@/types";

export const MOCK_LOCATIONS: GovernmentLocation[] = [
  // --- Balai Polis ---
  {
    id: "loc_bp_001",
    name: "Balai Polis Dang Wangi",
    category: "BALAI_POLIS",
    address: "Jalan Dang Wangi, 50480",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    features: ["BIM_SIGNER_KIOSK", "VISUAL_ALERTS", "VISUAL_QUEUE"],
    status: "ACTIVE",
    coordinates: { lat: 3.158, lng: 101.701 },
    hours: "Mon–Fri 8:00am – 5:00pm",
  },
  {
    id: "loc_bp_002",
    name: "Balai Polis Petaling Jaya",
    category: "BALAI_POLIS",
    address: "Jalan Templer, Seksyen 1, 46000",
    city: "Petaling Jaya",
    state: "Selangor",
    features: ["BIM_SIGNER_KIOSK", "SIGN_INTERPRETER"],
    status: "ACTIVE",
    coordinates: { lat: 3.107, lng: 101.607 },
    hours: "Mon–Sun 8:00am – 10:00pm",
  },
  {
    id: "loc_bp_003",
    name: "Balai Polis Brickfields",
    category: "BALAI_POLIS",
    address: "Jalan Tun Sambanthan, Brickfields, 50470",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    features: ["VISUAL_ALERTS", "INDUCTION_LOOP"],
    status: "ACTIVE",
    coordinates: { lat: 3.131, lng: 101.686 },
    hours: "24 hours",
  },
  {
    id: "loc_bp_004",
    name: "Balai Polis Georgetown",
    category: "BALAI_POLIS",
    address: "Jalan Penang, 10000",
    city: "Georgetown",
    state: "Pulau Pinang",
    features: ["BIM_SIGNER_KIOSK"],
    status: "COMING_SOON",
    coordinates: { lat: 5.414, lng: 100.329 },
  },

  // --- JPJ ---
  {
    id: "loc_jpj_001",
    name: "JPJ Kuala Lumpur",
    category: "JPJ",
    address: "Jalan Ipoh, Sentul, 51200",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    features: ["BIM_SIGNER_KIOSK", "SIGN_INTERPRETER", "VISUAL_QUEUE"],
    status: "ACTIVE",
    coordinates: { lat: 3.182, lng: 101.682 },
    hours: "Mon–Fri 8:00am – 5:00pm",
  },
  {
    id: "loc_jpj_002",
    name: "JPJ Shah Alam",
    category: "JPJ",
    address: "Persiaran Perbandaran, Seksyen 14, 40000",
    city: "Shah Alam",
    state: "Selangor",
    features: ["BIM_SIGNER_KIOSK", "VISUAL_ALERTS"],
    status: "ACTIVE",
    coordinates: { lat: 3.074, lng: 101.519 },
    hours: "Mon–Fri 8:00am – 5:00pm",
  },
  {
    id: "loc_jpj_003",
    name: "JPJ Pulau Pinang",
    category: "JPJ",
    address: "Jalan Anson, 10400",
    city: "Georgetown",
    state: "Pulau Pinang",
    features: ["BIM_SIGNER_KIOSK"],
    status: "COMING_SOON",
    coordinates: { lat: 5.409, lng: 100.336 },
  },
  {
    id: "loc_jpj_004",
    name: "JPJ Johor Bahru",
    category: "JPJ",
    address: "Jalan Ayer Molek, 80000",
    city: "Johor Bahru",
    state: "Johor",
    features: ["BIM_SIGNER_KIOSK"],
    status: "COMING_SOON",
    coordinates: { lat: 1.463, lng: 103.762 },
  },

  // --- Hospital / Klinik ---
  {
    id: "loc_hsp_001",
    name: "Hospital Kuala Lumpur",
    category: "HOSPITAL",
    address: "Jalan Pahang, 50586",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    features: ["SIGN_INTERPRETER", "VISUAL_ALERTS", "INDUCTION_LOOP"],
    status: "ACTIVE",
    coordinates: { lat: 3.169, lng: 101.7 },
    hours: "24 hours (Emergency); OPD Mon–Fri 8:00am – 5:00pm",
  },
  {
    id: "loc_hsp_002",
    name: "Hospital Selayang",
    category: "HOSPITAL",
    address: "Lebuhraya Selayang-Kepong, 68100",
    city: "Batu Caves",
    state: "Selangor",
    features: ["BIM_SIGNER_KIOSK", "VISUAL_ALERTS"],
    status: "ACTIVE",
    coordinates: { lat: 3.252, lng: 101.651 },
    hours: "24 hours",
  },
  {
    id: "loc_hsp_003",
    name: "Klinik Kesihatan Chow Kit",
    category: "HOSPITAL",
    address: "Jalan Raja Laut, Chow Kit, 50350",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    features: ["VISUAL_ALERTS", "VISUAL_QUEUE"],
    status: "ACTIVE",
    coordinates: { lat: 3.163, lng: 101.694 },
    hours: "Mon–Fri 8:00am – 5:00pm",
  },
  {
    id: "loc_hsp_004",
    name: "Hospital Pulau Pinang",
    category: "HOSPITAL",
    address: "Jalan Residensi, 10990",
    city: "Georgetown",
    state: "Pulau Pinang",
    features: ["BIM_SIGNER_KIOSK"],
    status: "COMING_SOON",
    coordinates: { lat: 5.418, lng: 100.312 },
  },
];
